### ISSUE TITLE
royaltyInfo function doesn't use _tokenId 

### ISSUE THREAD

**Issue by omer2307** [alxrnz2/ERC1155-with-EIP2981-for-OpenSea#1]
Hi, why should we get input of token ID if we don't use it within the function?

**Comment by alexrienzie** [comment]
Hey, so we left the token ID input to maintain consistency with the EIP [https://eips.ethereum.org/EIPS/eip-2981](EIP). Option to vary royalties by token by adding some code, which we didn't do in this contract.
