### ISSUE TITLE
Can a royalty distributed over all the NFT's of a collection?

### ISSUE THREAD

**Issue by sandorkonya** [alxrnz2/ERC1155-with-EIP2981-for-OpenSea#5]
For example, if i have a collection with 100 non-fungible token, and each that can be minted only 1 time, i would like to give a royalty to all toher 99 NFT owner whenever a transaction occurs on any of them.

Is it possible?

**Comment by alexrienzie** [comment]
Easiest way to do this would probably be to direct royalties to a splitter smart contract (e.g., [OpenZeppelin](https://docs.openzeppelin.com/contracts/2.x/api/payment)) that monitors ownership of your tokens.
