### ISSUE TITLE
How can I set the price? 

### ISSUE THREAD

**Issue by k-kaddal** [alxrnz2/ERC1155-with-EIP2981-for-OpenSea#6]
I can't find any param that deals with pricing except royaltyInfo(). 
How to set the pricing of an edition? or this is not implemented?

Do I misunderstand something?

**Comment by alexrienzie** [comment]
Hey, so ERC-1155/721 standards don't have functions for direct sales, only for transfers. Owners generally enter into separate smart contracts managed by exchanges to sell tokens, using the approval/approved functions in the ERC-1155/721 to grant transfer permissions to those separate contracts.

E.g., some of the OpenSea hacks emanate from vulnerabilities in their smart contracts vs. ERC-1155/721 standards.

[More on the ERC-1155 specifications](https://eips.ethereum.org/EIPS/eip-1155).
